#
# Makefile for 4365b0 ROM image build
#
# Broadcom Proprietary and Confidential. Copyright (C) 2017,
# All Rights Reserved.
# 
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of Broadcom;
# the contents of this file may not be disclosed to third parties, copied
# or duplicated in any form, in whole or in part, without the prior
# written permission of Broadcom.
#
# $Id: $
#
# top level make
#

CHIP = 4365b0

ROMTBL_VARIANT = pcie
ROMTBL_TGT = $(CHIP)/$(ROMTBL_VARIANT)

# CLM info
CLM_TYPE	:= min
TCAM_ONLY	:= 1
include ../Makefile.cmn
