/*
 *-----------------------------------------------------------------------------
 * Broadcom Proprietary and Confidential. Copyright (C) 2016,
 * All Rights Reserved.
 * 
 * This is UNPUBLISHED PROPRIETARY SOURCE CODE of Broadcom;
 * the contents of this file may not be disclosed to third parties, copied
 * or duplicated in any form, in whole or in part, without the prior
 * written permission of Broadcom.
 *-----------------------------------------------------------------------------
 *
 * DO NOT EDIT THIS FILE, IT WAS MACHINE GENERATED
 * by paulc on Tue Jul 29 10:24:24 2014 using:
 *
 *  $ txgaintables_tcl2c.py 47xxtcl wlc_phytbl_ac_gains.h wlc_phytbl_ac_gains.c
 *
 * $Id$
 */
/* FILE-CSTYLED */

#ifndef WLC_PHYTBL_AC_GAINS_H_
#define WLC_PHYTBL_AC_GAINS_H_

#include <typedefs.h>

#define TXGAIN_TABLES_LEN 384
extern const uint16 txgain_20691_phyrev13_2g_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20691_phyrev13_2g_ipa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20691_phyrev13_2g_point5_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20691_phyrev13_5g_1_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20691_phyrev13_5g_1_point5_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20691_phyrev13_5g_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20691_phyrev13_5g_ipa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20691_phyrev13_5g_point5_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20691_phyrev13_ipa_2g_for_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20691_phyrev16_2g_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20691_phyrev16_2g_ipa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20691_phyrev16_5g_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20691_phyrev16_5g_ipa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20693_phyrev12_2g_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20693_phyrev12_2g_ipa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20693_phyrev12_5g_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20693_phyrev12_5g_epa_rev10[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20693_phyrev12_5g_ipa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20693_phyrev12_5g_epa_die2[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20693_phyrev12_2g_epa_die2[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20693_phyrev32_2g_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_20693_phyrev32_5g_epa[TXGAIN_TABLES_LEN];
#endif /* WLC_PHYTBL_AC_GAINS_H_ */
